name: run-tests-on-push
on: [push]
jobs:
  run-gtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y liblog4cxx-dev
      - run: sudo git clone https://github.com/bluescarni/heyoka.git
      - run: cd heyoka
        working-directory: ./heyoka
      - run: mkdir build
        working-directory: ./build
      - run: cmake .. .
      - run: cmake --build . --target install
        working-directory: ../..
      - run: mkdir build
        working-directory: ./build
      - run: cmake .. .
      - run: cmake --build . --target debris_sim_test
      - run: ./debris_sim_test
